import prisma from "../../config/prismaClient.js";

// @desc    Get all checkins
// @route   GET /api/checkins
// @access  Private/Admin
const getCheckins = async (req, res) => {
  try {
    const checkins = await prisma.checkin.findMany({
      orderBy: { createdAt: "desc" },
    });
    res.status(200).json(checkins);
  } catch (error) {
    console.error("Error fetching checkins:", error);
    res.status(500).json({ message: "Failed to fetch checkins" });
  }
};

// @desc    Get single checkin
// @route   GET /api/checkins/:id
// @access  Private/Admin
const getCheckin = async (req, res) => {
  try {
    const checkin = await prisma.checkin.findUnique({
      where: { id: parseInt(req.params.id) },
    });
    if (checkin) {
      res.status(200).json(checkin);
    } else {
      res.status(404).json({ message: "Checkin not found" });
    }
  } catch (error) {
    console.error("Error fetching checkin:", error);
    res.status(500).json({ message: "Failed to fetch checkin" });
  }
};

// @desc    Create new checkin
// @route   POST /api/checkins
// @access  Private
const createCheckin = async (req, res) => {
  const { storeId, sessionId, checkoutTime } = req.body;
  // createdAt is auto-generated by Prisma
  try {
    const checkin = await prisma.checkin.create({
      data: {
        storeId,
        sessionId,
        checkoutTime: checkoutTime || "none", // Default from frontend
      },
    });
    res.status(201).json(checkin);
  } catch (error) {
    console.error("Error creating checkin:", error);
    res.status(500).json({ message: "Failed to create checkin" });
  }
};

// @desc    Update checkin
// @route   PUT /api/checkins/:id
// @access  Private
const updateCheckin = async (req, res) => {
  const { storeId, sessionId, checkoutTime } = req.body;
  try {
    const checkin = await prisma.checkin.update({
      where: { id: parseInt(req.params.id) },
      data: {
        storeId,
        sessionId,
        checkoutTime,
      },
    });
    res.status(200).json(checkin);
  } catch (error) {
    console.error("Error updating checkin:", error);
    res.status(500).json({ message: "Failed to update checkin" });
  }
};

// @desc    Delete checkin
// @route   DELETE /api/checkins/:id
// @access  Private/Admin
const deleteCheckin = async (req, res) => {
  try {
    await prisma.checkin.delete({
      where: { id: parseInt(req.params.id) },
    });
    res.status(200).json({ message: "Checkin deleted successfully" });
  } catch (error) {
    console.error("Error deleting checkin:", error);
    res.status(500).json({ message: "Failed to delete checkin" });
  }
};

export {
  getCheckins,
  getCheckin,
  createCheckin,
  updateCheckin,
  deleteCheckin,
};
